### ISSUE TITLE
Gulliver fails to fetch Icon from terra.com.br

### ISSUE THREAD

**Issue by andreban** [GoogleChrome/gulliver#125] opened 2016-09-08 17:13 UTC
Gulliver is failing to fetch the icon and displaying a broken image:

`https://www.terra.com.br/manifest-br.json`

**Comment by juliantoledo** [comment] 2016-09-08 17:38
I am also seeing few 403 because of cloudflare captchas. We need to investigate that too.

**Comment by ithinkihaveacat** [comment] 2016-09-13 12:58
FWIW, tried a few requests for this URL via benchmarking tools (from different IPs) and got 200 OK back 100% of the time. So this might be a difficult one to debug/workaround…

**Comment by juliantoledo** [comment] 2016-09-13 13:01
Thank you @ithinkihaveacat 
I will open a bug for the cloudflare captchas if I see the issue again and find steps to reproduce it.

**Comment by juliantoledo** [comment] 2016-09-13 13:02
The Terra once is fixed in the PR.

**Closed** 2016-09-15 15:41 UTC
Labels: bug
